language: node_js
node_js:
  - 4
  - 6
  - stable

notifications:
  slack:
		- secure: "vTWOS+mpUAS6uxPdDALjO7RKwKClRvoGf5PD2LK6aqQP2uynGxCKCQm261E9JVIkQYifR6IGc8Wu6CezxCv7bff/zgdcDFzRbXj84aQ/RJoCSEKs/kanPsHXuZW/QbJKPyW42zlytA7y3+8tp0KwrhFhBw0HBMzSm3QCtkUmDfPNHf9kwntmaJgSKYuDLAaRKGYaoaBZxa7oeObSGNda32QMQi+gk41YTgs0dtcbzjN5qaaVmEupW6O6I7b+fBCj60vn+Lp9Z6qgeY/yxb5xIuxndwnGEosy9Z6ZmBi2VNAMeBKdAxUrHLRV5gqwJxPYXUILVIlfscQ5IgfxbdAZ8vmjCrrn3T9YCcWCdv0a83hofDeNf17RGCk7mV29uPx0I6JhkbQTbD5e4cguxydKYgs8V9DQpvr/v9UbHX/rNeVuK/M4vyqliZM5QwLVt13LuOvvOqOW3ge/GNzvZKkdSDZwCrTlnn52i7pbOpwVnBShcpWGRhqx1qx8nQHY18Cc3Rd6UYwhLst7phjbcSGAY3XqIeRj24LAjLu0tEA5P+1nEWKsEsqFWC843RGGg6X5zJDt3EnR0emIjaRrG+OV1bl90CNN+4UYaWWrlsfiLCXiyhlafhd4fqXD+SqXjJr4OHznL7DSBuu0jYT2AOpTITiUCSbQL98AoDXhoC9UVhA="
